import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Use | Cidadão.AI',
  description: 'Terms and conditions for using Cidadão.AI. Learn about the rules and guidelines for using our public transparency system.',
  robots: 'index, follow',
  openGraph: {
    title: 'Terms of Use - Cidadão.AI',
    description: 'Rules and conditions for using the Cidadão.AI system',
    type: 'website',
    locale: 'en_US',
  },
}

export default function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <h1 className="text-4xl font-bold mb-8">Terms of Use</h1>

      <div className="prose prose-lg dark:prose-invert max-w-none">
        <p className="text-gray-600 dark:text-gray-400 mb-8">
          Last updated: {new Date().toLocaleDateString('en-US')}
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing and using Cidadão.AI, you agree to these terms of use. If you do not
            agree with any part of these terms, you should not use our platform.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">2. Service Description</h2>
          <p>
            Cidadão.AI is an academic public transparency system that uses artificial
            intelligence to facilitate access and analysis of Brazilian government data.
          </p>
          <p className="mt-4">
            This is an academic research project (undergraduate thesis) from IFSULDEMINAS and has no
            commercial character or official government affiliation.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">3. Acceptable Use</h2>
          <h3 className="text-xl font-medium mb-2">3.1 You May</h3>
          <ul className="list-disc pl-6 mb-4">
            <li>Conduct queries on government public data</li>
            <li>Use AI agents for transparency analysis</li>
            <li>Export investigation results for personal use</li>
            <li>Share findings of public interest</li>
          </ul>

          <h3 className="text-xl font-medium mb-2">3.2 You May Not</h3>
          <ul className="list-disc pl-6 mb-4">
            <li>Use the system for illegal or unethical purposes</li>
            <li>Attempt to access restricted areas or private data</li>
            <li>Overload the system with excessive requests</li>
            <li>Reproduce, modify, or distribute the code without authorization</li>
            <li>Use data for harassment, discrimination, or defamation</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">4. Data and Privacy</h2>
          <p>
            We only collect data necessary for system operation. Your queries
            and investigations are stored securely and are not shared with third parties.
          </p>
          <p className="mt-4">
            For more information, see our{' '}
            <a href="/en/privacy" className="text-green-600 hover:text-green-700 underline">
              Privacy Policy
            </a>.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
          <p>
            The Cidadão.AI source code is open source under the MIT license. You may:
          </p>
          <ul className="list-disc pl-6 mt-4">
            <li>View and study the code</li>
            <li>Modify for personal use</li>
            <li>Contribute improvements via pull requests</li>
          </ul>
          <p className="mt-4">
            Government data is public and property of the Brazilian government. Analysis
            and insights generated by AI agents are considered derivatives of public data.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">6. Disclaimer</h2>
          <div className="bg-yellow-50 dark:bg-yellow-900/20 p-6 rounded-lg">
            <p className="font-medium text-yellow-800 dark:text-yellow-200">
              Cidadão.AI is provided "as is", without warranties of any kind.
            </p>
            <ul className="list-disc pl-6 mt-4 text-yellow-700 dark:text-yellow-300">
              <li>We do not guarantee absolute accuracy of AI analyses</li>
              <li>We are not responsible for decisions made based on the data</li>
              <li>We recommend verifying information from official sources</li>
              <li>This is an academic project, not a substitute for professional consultation</li>
            </ul>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
          <p>
            Under no circumstances will Cidadão.AI, its developers, or the educational institution
            be liable for:
          </p>
          <ul className="list-disc pl-6 mt-4">
            <li>Direct, indirect, incidental, or consequential damages</li>
            <li>Loss of data, profits, or opportunities</li>
            <li>Business or service interruption</li>
            <li>Improper use of information obtained from the system</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">8. Service Availability</h2>
          <p>
            As an academic project, Cidadão.AI may be:
          </p>
          <ul className="list-disc pl-6 mt-4">
            <li>Temporarily unavailable for maintenance</li>
            <li>Subject to changes without prior notice</li>
            <li>Discontinued at the end of the academic project</li>
          </ul>
          <p className="mt-4">
            We will do our best to notify in advance about significant changes.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">9. Terms Modifications</h2>
          <p>
            We reserve the right to modify these terms at any time. Significant
            changes will be notified on the system's homepage.
          </p>
          <p className="mt-4">
            Continued use after modifications constitutes acceptance of the new terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">10. Applicable Law</h2>
          <p>
            These terms are governed by Brazilian law. Any disputes will be resolved
            in the competent courts of Brazil.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">11. Contact</h2>
          <p>
            For questions about these terms, please contact:
          </p>
          <div className="mt-4 p-4 bg-gray-50 dark:bg-gray-800 rounded-lg">
            <p className="font-medium">Anderson Henrique da Silva</p>
            <p className="text-gray-600 dark:text-gray-400">Developer and Researcher</p>
            <p className="text-gray-600 dark:text-gray-400">IFSULDEMINAS - Muzambinho Campus</p>
            <p className="mt-2">
              <a
                href="mailto:anderson.ufrj@gmail.com"
                className="text-green-600 hover:text-green-700 underline"
              >
                anderson.ufrj@gmail.com
              </a>
            </p>
          </div>
        </section>

        <section className="mb-8">
          <div className="bg-green-50 dark:bg-green-900/20 p-6 rounded-lg">
            <p className="font-medium text-green-800 dark:text-green-200">
              Thank you for using Cidadão.AI to promote public transparency!
            </p>
            <p className="mt-2 text-green-700 dark:text-green-300">
              Together, we make government data more accessible and understandable for all Brazilians.
            </p>
          </div>
        </section>
      </div>
    </div>
  )
}
